### PR TITLE
fix: use image manifests to extract the digest

### LINKED ISSUE #83: Alternative for `digest(repo, tag)` that works across implementations/behind proxys
The following method

https://github.com/deitch/docker_registry2/blob/bc64bc8255b6a2cce71484b2c8c983fdeb67cbb1/lib/registry/registry.rb#L141-L143

Assumes that there is a header `docker_content_digest` with `HEAD` requests, but that does not seem to be the case in every registry implementation. 

In my environment for example, that does not seem to be true as no header contains the digest. It is either dropped by the proxy or some other implementation detail of `Artifactory` 

```shell
curl --location --head 'https://myrepo/v2/azul/zulu-openjdk/manifests/10u01'
```

```
HTTP/1.1 200 
X-JFrog-Version: Artifactory/7.41.12 74112900
X-Artifactory-Id: redacted
X-Artifactory-Node-Id: redacted
Last-Modified: Mon, 17 Oct 2022 20:20:07 GMT
ETag: e84c7e494bfd66a6974b944753dee898b439713a
X-Checksum-Sha1: e84c7e494bfd66a6974b944753dee898b439713a
X-Checksum-Sha256: 03306384699b14e424c876616c6a7e802aed18d878b1ae97743d755fa224b648
X-Checksum-Md5: bfaca1f90fc67941df3fc5d0e47b39ed
Accept-Ranges: bytes
X-Artifactory-Filename: 10u01
Content-Disposition: attachment; filename="10u01"; filename*=UTF-8''10u01
Content-Type: application/octet-stream
Content-Length: 1781
Date: Fri, 21 Apr 2023 22:18:57 GMT
```

A `GET` request seems to be more consistent : 

```shell
curl --location --request GET 'https://myrepo/v2/azul/zulu-openjdk/manifests/10u01'
```

```json

{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 5161,
      "digest": "sha256:512e680fa77f97fbe695bd14716901d93553971d9607d672c0dbdb9a39ef7dfc"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 43026850,
         "digest": "sha256:297061f60c367c17cfd016c97a8cb24f5308db2c913def0f85d7a6848c0a17fa"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 850,
         "digest": "sha256:e9ccef17b516e916aa8abe7817876211000c27150b908bdffcdeeba938cd004c"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 621,
         "digest": "sha256:dbc33716854d9e2ef2de9769422f498f5320ffa41cb79336e7a88fbb6c3ef844"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 851,
         "digest": "sha256:8fe36b178d25214195af42254bc7d5d64a269f654ef8801bbeb0b6a70a618353"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 169,
         "digest": "sha256:686596545a94a0f0bf822e442cfd28fbd8a769f28e5f4018d7c24576dc6c3aac"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 5482050,
         "digest": "sha256:ab96c28488055d118b5c0edaccab106bad518ac0f95ad63c772d0407f57ffc84"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 211407284,
         "digest": "sha256:adcd61ac7c54f40837ac29cc72a172bca90fb70614fc8e11a2a21002824f160c"
      }
   ]
}

```

Maybe this will be more reliable? 

 ```ruby

 def digest(repo, tag)
tag_path = "/v2/#{repo}/manifests/#{tag}"
response = doget(tag_path)
JSON.parse(response.body)["config"]["digest"]

```

### PR DESCRIPTION
**Pull request by yeikel**
Fixes #83

### CODE REVIEW

File: lib/registry/registry.rb [hunk 1]
```diff
@@ -138,17 +126,33 @@ def blob(repo, digest, outpath = nil)
...
+    def digest(repo, tag, architecture = nil, os = nil)
+      manifest = manifest(repo, tag)
+      json_body = JSON.parse(manifest.body)
+
+      # Multi-arch images
+      if json_body.key?('manifests')
+        manifests = json_body['manifests']
+
+        raise DockerRegistry2::InvalidInput, 'Both architecture and os must be defined because this is a Multi-arch image' if architecture.nil? || os.nil?
+
```
Comment (yeikel) [inline lib/registry/registry.rb:138]: @deitch 

I need some help here with the design of parsing  `Multi-arch images` 

There a couple of decisions we need to make here

1. If there are multiple entries what should happen? 

I am currently filtering based on the new `architecture` and `os` parameters. if so: 

- What should happen if the user does not pass the os and  architecture parameters? I believe that we should throw an error as configured
- What should happen if there are no matches? I am currently returning `nil` but I think that should also throw an error there


- Return a custom object with with architecture, os, and digest?

- Return the raw manifests?

File: spec/docker_registry2_spec.rb [hunk 2]
```diff
@@ -80,7 +80,7 @@
       end
 
       it { expect { my_ubuntu_multiarch_manifest }.not_to raise_error }
-      it { expect(archs).to match_array(%w[amd64 amd64]) }
```
Comment (yeikel) [inline spec/docker_registry2_spec.rb:83]: I don't think that this test made sense as there should not be any image with the same architecture twice

**Comment by deitch** [comment]
Failing tests, and still draft. Let me know when it's ready for review.

**Comment by yeikel** [comment]
> Failing tests, and still draft. Let me know when it's ready for review.

I reverted the change to `rmtag` as I am not quite sure how that works or why it is failing.  The current integration tests are tricky to run locally. Do you have any guide about that? 

Updating this method is also not part of the original issue so we can revisit it in a future. We probably need to remove the dependency of `:docker_content_digest` header for that method as well

The pull request is ready for feedback now

File: spec/docker_registry2_spec.rb (hunk 2 above)
Comment (deitch) [reply spec/docker_registry2_spec.rb:83]: I didn't actually write the spec (and am appreciative to those who did), but I think you are right. How did it ever have both same arch?

Although, arguably, you _could_. The manifests in an index are in an array, so nothing is preventing duplication.

File: lib/registry/registry.rb (hunk 1 above)
Comment (deitch) [reply lib/registry/registry.rb:138]: > no matches

yeah, I would think that is an error. Maybe a custom one, so that someone can compare a generic error (e.g. could not reach the registry or auth) vs specifically could not match the requested platform.

> What should happen if the user does not pass the os and architecture parameters? I believe that we should throw an error as configured

I would think we should return the digest of the top-level object (likely an index).

**Comment by yeikel** [comment]
> > remove the dependency of :docker_content_digest header for that method as well
> 
> Does the docker registry (both the SaaS one at hub.docker.com and the container at `distribution/distribution`) provide both headers, such that the docker one is unneeded?

In this new implementation we are using the manifest body to avoid depending in that header that is only available in some implementations

File: lib/registry/registry.rb (hunk 1 above)
Comment (yeikel) [reply lib/registry/registry.rb]: I refactored it with the latest commit. Changes include: 

1. Throws `NotFound`  when it reaches the end of the manifest and it did not find anything
2. if architecture and os are not specified, it returns the first entry
3. if architecture is defined and os isn't, it returns the first entry that matches the architecture
4. if os isn't defined and architecture is, it returns the first entry that matches the os
5. Otherwise, it checks that both os and architecture  matches and returns that

Comment (deitch) [reply lib/registry/registry.rb]: > Throws NotFound when it reaches the end of the manifest and it did not find anything

👍 

> if architecture and os are not specified, it returns the first entry

And why not the index itself? The ordering is arbitrary, so it will be inconsistent between repos, or even tags of the same repo.

> if architecture is defined and os isn't, it returns the first entry that matches the architecture
> if os isn't defined and architecture is, it returns the first entry that matches the os

I think it would be better to have both or none. The actual OCI and docker stuff use "platform", which is a combination `os/arch[/variant]`, e.g. `linux/amd64` or `linux/arm64/v8`. Omitting just OS or arch returns an error (variant os optional).

Comment (yeikel) [reply lib/registry/registry.rb]: > And why not the index itself? The ordering is arbitrary, so it will be inconsistent between repos, or even tags of the same repo.

Is this appropriate in Ruby? I understand that we did not define any type, but I'd be surprised if a method that normally returns a string returns a object all of sudden

> I think it would be better to have both or none. The actual OCI and docker stuff use "platform", which is a combination os/arch[/variant], e.g. linux/amd64 or linux/arm64/v8. Omitting just OS or arch returns an error (variant os optional).

That's fair. Should we support variant as well?

Comment (yeikel) [reply lib/registry/registry.rb]: I updated and simplified it

it returns the `manifests` index if : 

- architecture and os are not specified
- architecture is defined and os isn't
- os isn't defined and architecture is

Otherwise, it checks that both os and architecture matches and returns the digest if found. Otherwise it throws `DockerRegistry2::NotFound`

Comment (yeikel) [reply lib/registry/registry.rb]: Added supports for `variant` as well

**Review by deitch — APPROVED** [review]

**Comment by deitch** [comment]
Hooray! Thanks!

**Comment by yeikel** [comment]
Thank you for reviewing and merging it :)

Do you have any release planned?

**Comment by deitch** [comment]
Sure, this is worth a minor release (according to semver anyways).

**Comment by deitch** [comment]
Done. Give it a few mins for CI to run through pushing it all out.

**Comment by yeikel** [comment]
> Done. Give it a few mins for CI to run through pushing it all out.

Thank you for your help!
